apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: karpenter-reserved-capacity-demo
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: karpenter-aws-demo
      containers:
        - name: inflate
          image: k8s.gcr.io/pause
          resources:
            requests:
              cpu: 1
              memory: 1Gi
