apiVersion: v1
kind: Namespace
metadata:
  name: karpenter-custom-kube-scheduler-demo
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: od-mng-4vcp-16gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  replicas: 1
  type: AWSEKSNodeGroup
  id: ${OD_NODE_GROUP_ARN}
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: spot-mng-4vcp-16gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  replicas: 1
  type: AWSEKSNodeGroup
  id: ${SPOT_NODE_GROUP1_ARN}
---  
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: spot-mng-8vcp-32gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  replicas: 1
  type: AWSEKSNodeGroup
  id: ${SPOT_NODE_GROUP1_ARN}  
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: od-mng-4vcp-16gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: od-mng-4vcp-16gb
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - prometheus:
        query: karpenter_reserved_capacity_cpu_utilization{name="od-mng-4vcp-16gb"}
        target:
          type: Utilization
          value: 60
    - prometheus:
        query: karpenter_reserved_capacity_memory_utilization{name="od-mng-4vcp-16gb"}
        target:
          type: Utilization
          value: 60
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: spot-mng-4vcp-16gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: spot-mng-4vcp-16gb
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - prometheus:
        query: karpenter_reserved_capacity_cpu_utilization{name="spot-mng-4vcp-16gb"}
        target:
          type: Utilization
          value: 60
    - prometheus:
        query: karpenter_reserved_capacity_memory_utilization{name="spot-mng-4vcp-16gb"}
        target:
          type: Utilization
          value: 60
---          
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: spot-mng-8vcp-32gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: spot-mng-8vcp-32gb
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - prometheus:
        query: karpenter_reserved_capacity_cpu_utilization{name="spot-mng-8vcp-32gb"}
        target:
          type: Utilization
          value: 60
    - prometheus:
        query: karpenter_reserved_capacity_memory_utilization{name="spot-mng-8vcp-32gb"}
        target:
          type: Utilization
          value: 60          

---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: od-mng-4vcp-16gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  reservedCapacity:
    nodeSelector:
      eks.amazonaws.com/nodegroup: od-mng-4vcp-16gb

---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: spot-mng-4vcp-16gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  reservedCapacity:
    nodeSelector:
      eks.amazonaws.com/nodegroup: spot-mng-4vcp-16gb
---      
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: spot-mng-8vcp-32gb
  namespace: karpenter-custom-kube-scheduler-demo
spec:
  reservedCapacity:
    nodeSelector:
      eks.amazonaws.com/nodegroup: spot-mng-8vcp-32gb      